inherit_settings: True

multiprocess: True
num_processes: 2
cleanup_pipeline_after_run: True

slice_geography: TRACT

# Steps for base mode
# ------------------------------------------------------------------
models:
  ### mp_seed_balancing step
  - input_pre_processor
  - setup_data_structures
  - initial_seed_balancing
  - meta_control_factoring
  - final_seed_balancing
  - integerize_final_seed_weights
  - sub_balancing.geography=TRACT
  ### mp_sub_balancing_TAZ step
  - sub_balancing.geography=TAZ
  ### mp_summarize step
  - expand_households
  - summarize
  - write_synthetic_population
  - write_data_dictionary
  - write_tables

#resume_after: integerize_final_seed_weights
resume_after:

multiprocess_steps:
  - name: mp_seed_balancing
    begin: input_pre_processor
  - name: mp_sub_balancing_TAZ
    begin: sub_balancing.geography=TAZ
    num_processes: 2
    slice:
      tables:
        - slice_crosswalk
        - crosswalk
      # don't slice any tables not explicitly listed above in slice.tables
      except: True
      # the following tables are added by sub_balancer and should be coalesced
      coalesce:
        - TAZ_weights
        - TAZ_weights_sparse
        - trace_TAZ_weights
  - name: mp_summarize
    begin: expand_households

# Rather than using the 'except: True' wildcard, we could explicitly list the tables that shold not be sliced
# and let activitysim.mp_tasks deduce which created tables should be coalesced, but that requires a pathalogical
# knowledge of the names of esisting internal tables, whereas the coalesce directive allows us to simply specify
# the names of the new tables we expect mp_sub_balancing_TAZ to create, which seems less error-prone
# (especially since mp_tasks.coalesce_pipelines will complain if the tables int het coalesce list are not found.)

# multiprocess_steps:
#   - name: mp_seed_balancing
#     begin: input_pre_processor
#   - name: mp_sub_balancing_TAZ
#     begin: sub_balancing.geography=TAZ
#     num_processes: 2
#     slice:
#       tables:
#         - slice_crosswalk
#         - crosswalk
#       except:
#         - geo_cross_walk
#         - TRACT_control_data
#         - TRACT_controls
#         - TRACT_weights
#         - TRACT_weights_sparse
#         - trace_TRACT_weights
#   - name: mp_summarize
#     begin: expand_households
