####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  TAZ: 100
  TRACT: 10200


# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables for repop mode
# (other required tables will already have been read into the
# pipeline by the input_pre_processor step if the initial run)
# ------------------------------------------------------------------
input_table_list:
  - filename : repop_control_totals_taz.csv
    tablename: TAZ_control_data


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name for repop mode
# ------------------------------------------------------------------
repop_control_file_name: repop_controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - expanded_household_ids
    - summary_TAZ


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - NP
      - AGEHOH
      - HHINCADJ
      - NWESR
  persons:
    filename: synthetic_persons.csv
    columns:
      - per_num
      - AGEP
      - OSUTAG
      - OCCP


# Steps for repop mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor.repop
    - repop_setup_data_structures
    - initial_seed_balancing.final=true;repop
    - integerize_final_seed_weights.repop
    - repop_balancing
    # expand_households options are append or replace
    - expand_households.repop;append
    - summarize.repop
    - write_synthetic_population.repop
    - write_tables.repop

  resume_after: summarize
